baseURL = "https://dadosdr.netlify.app/"
languageCode = "en-us"
title = "DadosDR"
theme = "hugo-arcana"
copyright = "© DadosDR - LAboratório do Desenvolvimento Regional - All rights reserved. | Contact OHBM-DIC"

[taxonomies]
    tag = "tags"

[params]
    description = "A website for the Diversity and Inclusivity Committee of the Organization for Human Brain Mapping."
    show_post_dates = false

    [[params.social]]
        title = "Twitter"
        icon = "fa-twitter"
        url = "https://twitter.com/ohbm?lang=en"
    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "https://www.facebook.com/humanbrainmapping.org/"
    [[params.social]]
        title = "DIC GitHub"
        icon = "fa-github"
        url = "https://github.com/ohbmdic"
    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "https://www.linkedin.com/company/organization-for-human-brain-mapping/about/"
    [[params.social]]
        title = "YouTube"
        icon = "fa-youtube"
        url = "https://www.youtube.com/@OHBM"


    [params.footer]

        [[params.footer.links]]
            header = "Links"
        [[params.footer.links.links]]
            title = "UFFS"
            url = "https://www.uffs.edu.br/"
        [[params.footer.links.links]]
            title = "UFFS"
            url = "https://www.uffs.edu.br/"
        [[params.footer.links.links]]
            title = "OHBM OnDemand"
            url = "https://www.pathlms.com/ohbm"
        [[params.footer.links.links]]
            title = "UFFS"
            url = "https://www.uffs.edu.br/"
        [[params.footer.links.links]]
            title = "UFFS"
            url = "https://www.uffs.edu.br/"

        [[params.footer.links]]
            header = "More Links"
        [[params.footer.links.links]]
            title = "UFFS"
            url = "https://www.uffs.edu.br/"
        [[params.footer.links.links]]
            title = "UFFS"
            url = "https://www.uffs.edu.br/"
        [[params.footer.links.links]]
            title = "UFFS"
            url = "https://www.uffs.edu.br/"
        [[params.footer.links.links]]
            title = "UFFS"
            url = "https://www.uffs.edu.br/"
        [[params.footer.links.links]]
            title = "UFFS"
            url = "https://www.uffs.edu.br/"          
            
        [params.footer.contact_form]
            enabled = true
            header = "Entre em contato"
            action = "mailto:felipesmolski@hotmail.com"

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'