baseURL = "https://ohbm-dic.github.io/"
languageCode = "en-us"
title = "OHBM DIC"
theme = "hugo-arcana"
copyright = "© Organization for Human Brain Mapping - Diversity and Inclusivity Committee. All rights reserved. | Contact OHBM-DIC"

[taxonomies]
    tag = "tags"

[params]
    description = "A website for the Diversity and Inclusivity Committee of the Organization for Human Brain Mapping."
    show_post_dates = false

    [[params.social]]
        title = "Twitter"
        icon = "fa-twitter"
        url = "https://twitter.com/ohbm?lang=en"
    [[params.social]]
        title = "Facebook"
        icon = "fa-facebook-f"
        url = "https://www.facebook.com/humanbrainmapping.org/"
    [[params.social]]
        title = "DIC GitHub"
        icon = "fa-github"
        url = "https://github.com/ohbmdic"
    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "https://www.linkedin.com/company/organization-for-human-brain-mapping/about/"
    [[params.social]]
        title = "YouTube"
        icon = "fa-youtube"
        url = "https://www.youtube.com/@OHBM"


    [params.footer]

        [[params.footer.links]]
            header = "Links"
        [[params.footer.links.links]]
            title = "OHBM Website"
            url = "https://www.humanbrainmapping.org/i4a/pages/index.cfm?pageid=1"
        [[params.footer.links.links]]
            title = "OHBM Blog"
            url = "https://www.ohbmbrainmappingblog.com/"
        [[params.footer.links.links]]
            title = "OHBM OnDemand"
            url = "https://www.pathlms.com/ohbm"
        [[params.footer.links.links]]
            title = "OHBM Tutorials"
            url = "https://www.ohbmbrainmappingblog.com/tutorials.html"
        [[params.footer.links.links]]
            title = "OHBM Engage"
            url = "https://www.humanbrainmapping.org/i4a/pages/index.cfm?pageid=3931"

        [[params.footer.links]]
            header = "More Links"
        [[params.footer.links.links]]
            title = "OHBM Open Science SIG"
            url = "https://ossig.netlify.app/"
        [[params.footer.links.links]]
            title = "OHBM Potcast"
            url = "https://www.youtube.com/watch?v=7birD1brLIo&list=PLEJ899jsgdRqhzWm2acsmIKFB1LO_JKwc"
        [[params.footer.links.links]]
            title = "COBIDAS"
            url = "https://www.humanbrainmapping.org/files/2016/COBIDASreport.pdf"
        [[params.footer.links.links]]
            title = "Aperture Neuro"
            url = "https://www.humanbrainmapping.org/i4a/pages/index.cfm?pageid=4121"
        [[params.footer.links.links]]
            title = "Imaging Neuroscience"
            url = "https://imaging-neuroscience.org/"             
            
        [params.footer.contact_form]
            enabled = true
            header = "Get In Touch"
            action = "mailto:ohbmdic@gmail.com"

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'