[[main]]
    name = "Dropdown"
    weight = 30
[[main]]
    parent = "Dropdown"
    name = "Lorem dolor"
    weight = 31
[[main]]
    parent = "Dropdown"
    name = "Magna Phasellus"
    weight = 32
[[main]]
    parent = "Dropdown"
    name = "Etiam sed tempus"
    weight = 33
[[main]]
    parent = "Dropdown"
    name = "Submenu"
    weight = 34
[[main]]
    parent = "Submenu"
    name = "Lorem dolor"
    identifier = "sub-lorem"
    weight = 35
[[main]]
    parent = "Submenu"
    name = "Phasellus magna"
    weight = 36
[[main]]
    parent = "Submenu"
    name = "Magna phasellus"
    weight = 37
[[main]]
    parent = "Submenu"
    name = "Etiam nisl"
    weight = 38
[[main]]
    parent = "Submenu"
    name = "Veroeros feugiat"
    identifier = "sub-veroeros"
    weight = 39
[[main]]
    parent = "Dropdown"
    name = "Veroeros feugiat"
    weight = 40
[[main]]
    name = "Dados"
    weight = 31
[[main]]
    parent = "Dados"
    name = "Bancos de Dados"
    url = "/dados_e_informacoes/banco_de_dados"
    weight = 31
[[main]]
    parent = "Dados"
    name = "Pesquisas Locais"
    weight = 31
[[main]]
    parent = "Dados"
    name = "Observatórios"
    weight = 31
[[main]]
    parent = "Dados"
    name = "Qualis (CAPES)"
    weight = 31
[menu]
[[menu.footer]]
    name = 'Terms'
    pageRef = '/terms'
    weight = 10
[[menu.footer]]
    name = 'Privacy'
    pageRef = '/privacy'
    weight = 20